version: "3"

networks:
  inception:

services:
  nginx:
    networks:
      - inception
    build:
      context: requirements/nginx/
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - $WP_VOL:/var/www/html
    restart: unless-stopped
  
  wordpress:
    networks:
      - inception
    build: 
      context: requirements/wordpress/
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - $WP_VOL:/var/www/html
    restart: unless-stopped

  mariadb:
    networks:
      - inception
    build:
      context: requirements/mariadb/
    ports:
      - 3306:3306
    volumes:
      - $DB_VOL:/var/lib/mysql
    container_name: mariadb
    restart: unless-stopped
