version: "3.3"

networks:
  inception:

services:
  mariadb:
    networks:
      - inception
    build:
      context: requirements/mariadb/
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - /home/msamual/data/db:/var/lib/mysql
    container_name: mariadb
    restart: always

  nginx:
    networks:
      - inception
    build:
      context: requirements/nginx/
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/msamual/data/wp:/var/www/html
    restart: always

  wordpress:
    networks:
      - inception
    build: 
      context: requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - /home/msamual/data/wp:/var/www/html
    restart: always
